spring:
  cloud:
    stream:
      binders:
        kafkaBinder:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: ${kafka.url}
              cloud:
                stream:
                  kafka:
                    streams:
                      binder:
                        autoCreateTopics: true
      bindings:
        event-out-0:
          destination: sample-event
          binder: kafkaBinder